# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    container_name: sancaka-db
    image: postgres:16.8-alpine3.20
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./volumes/sancaka-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sancaka
      POSTGRES_PASSWORD: sancakapass1234
      POSTGRES_DB: sancaka
    networks:
      - sancaka-network

  redis:
    container_name: sancaka-redis
    image: redis:8.0-rc1-alpine
    restart: always
    ports:
      - 6300:6379
    networks:
      - sancaka-network

  subscriber:
    build:
      context: .
      dockerfile: ./subscriber/Dockerfile
    container_name: sancaka-subscriber
    depends_on:
      - redis
    networks:
      - sancaka-network

  app: 
    build: 
      context: .
    container_name: sancaka-app 
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis 
      - subscriber
    networks:
      - sancaka-network

networks:
  sancaka-network:
    driver: bridge
